//! HTML packaging of the diagram viewer.
//!
//! The viewer is three assets under `viewer/`: the pure SVG renderer, the
//! interactive shell and its stylesheet, plus the ELK layout engine. This
//! module bundles them with a model's diagrams, either as a standalone page
//! ([`standalone_html`]) or as parts to splice into another document
//! ([`viewer_parts`], used by the architecture explorer).
//!
//! Native builds inline the layout engine so the output works offline. Other
//! targets (WebAssembly) reference the identical file on a CDN, pinned by a
//! subresource-integrity hash, rather than carrying 1.6 MB in the module.

use super::{elk, DiagramSet};
use serde_json::json;

/// Version of the vendored layout engine (`viewer/vendor/elk.bundled.js`).
pub const ELK_VERSION: &str = "0.9.3";
/// Subresource-integrity hash of that file; `html_tests` checks it matches.
pub const ELK_INTEGRITY: &str =
    "sha384-KO35c6PFq7tFxAEx6FtATwL9vOBOmCzQYr7GM0iTr3oO22s7Jc9OkclOH4AV7jwK";

const RENDER_JS: &str = include_str!("viewer/arcviz-render.js");
const LINKS_JS: &str = include_str!("viewer/arcviz-links.js");
const NAVIGATION_JS: &str = include_str!("viewer/arcviz-navigation.js");
const COLLAPSE_JS: &str = include_str!("viewer/arcviz-collapse.js");
const SCOPE_JS: &str = include_str!("viewer/arcviz-scope.js");
const EXPORT_JS: &str = include_str!("viewer/arcviz-export.js");
const STAGE_JS: &str = include_str!("viewer/arcviz-stage.js");
const PLACE_JS: &str = include_str!("viewer/arcviz-place.js");
const VIEWER_JS: &str = include_str!("viewer/arcviz-viewer.js");
const VIEWER_CSS: &str = include_str!("viewer/arcviz-viewer.css");
#[cfg(feature = "native")]
const ELK_JS: &str = include_str!("viewer/vendor/elk.bundled.js");

/// Id of the element the viewer mounts into.
pub const HOST_ID: &str = "arcviz-viewer";

/// The viewer, ready to splice into a host document.
pub struct ViewerParts {
    /// A `<style>` element; belongs in `<head>`.
    pub style: String,
    /// The mount point, the embedded diagram data and the scripts; belongs
    /// where the diagrams should appear.
    pub body: String,
}

/// Build the viewer for a model's diagrams. `title` names the model in
/// exported file names.
pub fn viewer_parts(set: &DiagramSet, title: &str) -> ViewerParts {
    let payload = json!({
        "title": title,
        "graphs": set.diagrams.iter().map(elk::to_elk).collect::<Vec<_>>(),
        "diagnostics": set.diagnostics,
        "links": set.links,
        "layout": set.layout,
        "layout_name": set.layout_name,
    });
    let body = format!(
        "<div id=\"{HOST_ID}\"></div>\n\
         <script type=\"application/json\" id=\"arcviz-data\">{data}</script>\n\
         {engine}\n\
         <script>{render}</script>\n\
         <script>{links}</script>\n\
         <script>{navigation}</script>\n\
         <script>{collapse}</script>\n\
         <script>{scope}</script>\n\
         <script>{export}</script>\n\
         <script>{stage}</script>\n\
         <script>{place}</script>\n\
         <script>{viewer}</script>\n\
         <script>window.arcvizViewer = ArcViz.mount(\
         document.getElementById('{HOST_ID}'), \
         JSON.parse(document.getElementById('arcviz-data').textContent), \
         {{ ELK: ELK, render: ArcVizRender, links: ArcVizLinks, \
         navigation: ArcVizNavigation, collapse: ArcVizCollapse, \
         scope: ArcVizScope, exporter: ArcVizExport, stage: ArcVizStage, \
         place: ArcVizPlace }});</script>",
        data = json_for_script(&payload),
        engine = engine_script(),
        render = inline_script(RENDER_JS),
        links = inline_script(LINKS_JS),
        navigation = inline_script(NAVIGATION_JS),
        collapse = inline_script(COLLAPSE_JS),
        scope = inline_script(SCOPE_JS),
        export = inline_script(EXPORT_JS),
        stage = inline_script(STAGE_JS),
        place = inline_script(PLACE_JS),
        viewer = inline_script(VIEWER_JS),
    );
    ViewerParts {
        style: format!("<style>{VIEWER_CSS}</style>"),
        body,
    }
}

/// A complete, self-contained HTML page showing a model's diagrams.
pub fn standalone_html(set: &DiagramSet, title: &str) -> String {
    let parts = viewer_parts(set, title);
    format!(
        "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n\
         <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n\
         <meta name=\"generator\" content=\"ArcLang {version}\">\n\
         <title>{title} — architecture diagrams</title>\n\
         <style>{page_css}</style>\n{style}\n</head>\n<body>\n\
         <header class=\"page-head\"><h1>{title}</h1><p>Architecture diagrams</p></header>\n\
         <main>\n{body}\n</main>\n\
         <footer class=\"page-foot\">Generated by ArcLang {version}. Layout by ELK {elk}.</footer>\n\
         </body>\n</html>\n",
        version = env!("CARGO_PKG_VERSION"),
        title = escape_html(title),
        page_css = PAGE_CSS,
        style = parts.style,
        body = parts.body,
        elk = ELK_VERSION,
    )
}

/// Page frame for the standalone document. System faces only: the file must
/// open offline, so it fetches no fonts.
const PAGE_CSS: &str = "\
:root{--ink:#18222d;--muted:#55616d;--rule:#c9d1d9;--paper:#f7f8f9}\
*{box-sizing:border-box}\
body{background:var(--paper);color:var(--ink);\
font-family:'Avenir Next','Segoe UI','Helvetica Neue',Arial,sans-serif;margin:0}\
.page-head{align-items:baseline;border-bottom:2px solid var(--ink);display:flex;\
flex-wrap:wrap;gap:.25rem 1rem;margin:0 auto;max-width:96rem;\
padding:clamp(1rem,.6rem + 1.6vw,2rem) clamp(1rem,.4rem + 2.4vw,2.5rem) .75rem}\
.page-head h1{font-size:clamp(1.25rem,1rem + 1vw,1.75rem);font-weight:700;\
letter-spacing:-.01em;line-height:1.2;margin:0}\
.page-head p{color:var(--muted);margin:0}\
main{margin:0 auto;max-width:96rem;padding:.5rem clamp(1rem,.4rem + 2.4vw,2.5rem) 2rem}\
.page-foot{color:var(--muted);font-size:.8125rem;margin:0 auto;max-width:96rem;\
padding:0 clamp(1rem,.4rem + 2.4vw,2.5rem) 2rem}\
@media print{body{background:#fff}.page-foot{display:none}}";

#[cfg(feature = "native")]
fn engine_script() -> String {
    format!("<script>{}</script>", inline_script(ELK_JS))
}

#[cfg(not(feature = "native"))]
fn engine_script() -> String {
    format!(
        "<script src=\"https://unpkg.com/elkjs@{ELK_VERSION}/lib/elk.bundled.js\" \
         integrity=\"{ELK_INTEGRITY}\" crossorigin=\"anonymous\"></script>"
    )
}

/// JavaScript made safe to inline: a `</script` inside it would end the
/// element early. `<\/script` is the same token to the JavaScript parser.
fn inline_script(source: &str) -> String {
    source
        .replace("</script", "<\\/script")
        .replace("</SCRIPT", "<\\/SCRIPT")
}

/// JSON made safe inside a `<script type="application/json">` element: no
/// `<` survives, so model text can neither close the element nor open a
/// comment. `<` parses back to `<`.
fn json_for_script(value: &serde_json::Value) -> String {
    value.to_string().replace('<', "\\u003c")
}

fn escape_html(text: &str) -> String {
    text.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::compiler::diagram::build_diagrams;
    use crate::compiler::{Compiler, CompilerConfig};

    fn set_of(source: &str) -> DiagramSet {
        let result = Compiler::new(CompilerConfig::default())
            .compile_string(source)
            .expect("compiles");
        build_diagrams(&result.ast)
    }

    #[test]
    fn model_text_cannot_break_out_of_the_data_element() {
        let set = set_of(
            r#"
logical_architecture LA {
  component Evil {
    description: "</script><script>alert(1)</script><!--"
  }
}
"#,
        );
        let parts = viewer_parts(&set, "</script><b>");

        let start = parts
            .body
            .find("id=\"arcviz-data\">")
            .expect("data element")
            + "id=\"arcviz-data\">".len();
        let end = start
            + parts.body[start..]
                .find("</script>")
                .expect("data element closes");
        let data = &parts.body[start..end];
        assert!(!data.contains('<'), "raw '<' in embedded JSON");
        let parsed: serde_json::Value = serde_json::from_str(data).expect("still valid JSON");
        assert_eq!(parsed["title"], "</script><b>");
        assert_eq!(
            parsed["graphs"][0]["children"][0]["arc"]["properties"]["description"],
            "</script><script>alert(1)</script><!--"
        );
    }

    #[test]
    fn standalone_page_escapes_the_title_and_mounts_the_viewer() {
        let set =
            set_of("logical_architecture LA {\n  component C {\n    description: \"c\"\n  }\n}\n");
        let html = standalone_html(&set, "A <b> & C");

        assert!(html.contains("<title>A &lt;b&gt; &amp; C — architecture diagrams</title>"));
        assert!(html.contains("<div id=\"arcviz-viewer\"></div>"));
        assert!(html.contains("ArcViz.mount("));
        assert!(html.starts_with("<!DOCTYPE html>"));
    }

    #[test]
    fn inlined_scripts_contain_no_closing_script_tag() {
        for source in [RENDER_JS, LINKS_JS, NAVIGATION_JS, COLLAPSE_JS, SCOPE_JS, EXPORT_JS, STAGE_JS, PLACE_JS, VIEWER_JS] {
            assert!(!inline_script(source).to_lowercase().contains("</script"));
        }
    }

    #[cfg(feature = "native")]
    #[test]
    fn native_output_is_self_contained() {
        let set =
            set_of("logical_architecture LA {\n  component C {\n    description: \"c\"\n  }\n}\n");
        let html = standalone_html(&set, "Offline");

        assert!(!html.contains("src=\"http"), "no script may be fetched");
        assert!(
            !html.contains("href=\"http"),
            "no stylesheet may be fetched"
        );
        assert!(!inline_script(ELK_JS).to_lowercase().contains("</script"));
    }

    #[cfg(feature = "native")]
    #[test]
    fn integrity_hash_matches_the_vendored_engine() {
        use sha2::Digest;
        const ALPHABET: &[u8; 64] =
            b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
        let digest = sha2::Sha384::digest(ELK_JS.as_bytes());
        // SHA-384 is 48 bytes: a whole number of 3-byte groups, no padding.
        let encoded: String = digest
            .chunks(3)
            .flat_map(|group| {
                let bits =
                    (u32::from(group[0]) << 16) | (u32::from(group[1]) << 8) | u32::from(group[2]);
                [18, 12, 6, 0].map(|shift| char::from(ALPHABET[((bits >> shift) & 63) as usize]))
            })
            .collect();
        assert_eq!(ELK_INTEGRITY, format!("sha384-{encoded}"));
    }
}
