//! C99 interface-contract export — the bridge from the architecture dossier
//! to the first day of implementation.
//!
//! Generates ONE header containing exactly what the model knows: data types
//! (enums, structs), message types for exchange items, per-component port
//! prototypes (in-port handlers, out-port senders) and state-machine
//! enums/step prototypes. NO behaviour is generated — the model does not
//! know it, so the export does not pretend to.

use super::ast::{Model, PortDirection};
use super::semantic::SemanticModel;

/// snake_case C identifier from any model name.
fn c_ident(raw: &str) -> String {
    let mut out = String::new();
    let mut prev_lower = false;
    for ch in raw.chars() {
        if ch.is_ascii_alphanumeric() {
            if ch.is_ascii_uppercase() && prev_lower {
                out.push('_');
            }
            out.push(ch.to_ascii_lowercase());
            prev_lower = ch.is_ascii_lowercase() || ch.is_ascii_digit();
        } else if !out.is_empty() && !out.ends_with('_') {
            out.push('_');
            prev_lower = false;
        }
    }
    let trimmed = out.trim_matches('_').to_string();
    let mut ident = if trimmed.is_empty() { "x".into() } else { trimmed };
    if ident.chars().next().unwrap().is_ascii_digit() {
        ident.insert(0, '_');
    }
    ident
}

fn c_type(attr_type: &str) -> &'static str {
    match attr_type.to_ascii_lowercase().as_str() {
        "int" | "integer" | "i32" => "int32_t",
        "i64" | "long" => "int64_t",
        "u32" | "uint" => "uint32_t",
        "u8" | "byte" => "uint8_t",
        "float" | "f32" => "float",
        "double" | "f64" | "real" => "double",
        "bool" | "boolean" => "bool",
        "string" | "str" | "text" => "const char *",
        _ => "uint8_t /* opaque */",
    }
}

pub fn generate_c_headers(model: &SemanticModel, ast: &Model) -> String {
    let model_name = model.name.clone().unwrap_or_else(|| "arclang_model".into());
    let guard = format!("ARCLANG_{}_INTERFACES_H", c_ident(&model_name).to_uppercase());
    let mut out = String::new();

    out.push_str(&format!(
        "/*\n * Interface contracts generated by ArcLang from model \"{model_name}\".\n \
         * Contracts only — behaviour is NOT generated. Regeneration is\n \
         * deterministic: a diff in this file means the architecture changed.\n */\n"
    ));
    out.push_str(&format!("#ifndef {guard}\n#define {guard}\n\n"));
    out.push_str("#include <stdint.h>\n#include <stdbool.h>\n#include <stddef.h>\n\n");

    // ---- Enumerations & scalar types from the data model ----
    if !ast.data_types.is_empty() {
        out.push_str("/* ==== Data types ==== */\n\n");
    }
    for dt in &ast.data_types {
        let name = c_ident(&dt.name);
        if let Some(values) = &dt.enumeration_values {
            out.push_str(&format!("typedef enum {{\n"));
            for (i, v) in values.iter().enumerate() {
                let vname = format!("{}_{}", name.to_uppercase(), c_ident(&v.name).to_uppercase());
                match &v.value {
                    Some(explicit) => out.push_str(&format!("    {vname} = {explicit},\n")),
                    None => out.push_str(&format!("    {vname} = {i},\n")),
                }
            }
            out.push_str(&format!("}} {name}_t;\n\n"));
        } else if let Some(base) = &dt.base_type {
            out.push_str(&format!("typedef {} {name}_t;\n\n", c_type(base)));
        }
    }

    // ---- Structs from classes ----
    for class in &ast.classes {
        let name = c_ident(&class.name);
        out.push_str(&format!("typedef struct {{\n"));
        if class.fields.is_empty() {
            out.push_str("    uint8_t _reserved; /* no fields modeled */\n");
        }
        for field in &class.fields {
            out.push_str(&format!(
                "    {} {};\n",
                c_type(&field.attr_type),
                c_ident(&field.name)
            ));
        }
        out.push_str(&format!("}} {name}_t;\n\n"));
    }

    // ---- Message types from exchange items ----
    if !ast.exchange_items.is_empty() {
        out.push_str("/* ==== Exchange items (messages) ==== */\n\n");
    }
    for item in &ast.exchange_items {
        let name = c_ident(&item.name);
        out.push_str(&format!(
            "/* mechanism: {} */\ntypedef struct {{\n",
            item.stereotype
        ));
        if item.attributes.is_empty() {
            out.push_str("    const void *payload;\n    size_t payload_len;\n");
        }
        for attr in &item.attributes {
            out.push_str(&format!(
                "    {} {};\n",
                c_type(&attr.attr_type),
                c_ident(&attr.name)
            ));
        }
        out.push_str(&format!("}} {name}_msg_t;\n\n"));
    }

    // ---- Per-component port contracts ----
    let item_type = |port_name: &str| -> String {
        // A port whose name matches an exchange item gets its typed message.
        for item in &ast.exchange_items {
            if c_ident(&item.name) == c_ident(port_name) {
                return format!("{}_msg_t", c_ident(&item.name));
            }
        }
        "void".into()
    };

    out.push_str("/* ==== Component interfaces ==== */\n\n");
    for la in &ast.logical_architecture {
        for comp in &la.components {
            let comp_id = if comp.id.is_empty() { &comp.name } else { &comp.id };
            let prefix = c_ident(comp_id);
            out.push_str(&format!(
                "/* ---- {} ({}) ---- */\n",
                comp.name, comp_id
            ));
            let arg_for = |name: &str| -> String {
                let ptype = item_type(name);
                if ptype == "void" {
                    "const void *payload, size_t payload_len".to_string()
                } else {
                    format!("const {ptype} *msg")
                }
            };
            for port in &comp.ports {
                let pname = c_ident(&port.name);
                let arg = arg_for(&port.name);
                match port.direction {
                    PortDirection::In => out.push_str(&format!(
                        "/* port in {} — implement this handler */\nvoid {prefix}_on_{pname}({arg});\n",
                        port.name
                    )),
                    PortDirection::Out | PortDirection::InOut => out.push_str(&format!(
                        "/* port out {} — provided by the integration layer */\nvoid {prefix}_send_{pname}({arg});\n",
                        port.name
                    )),
                }
            }
            // Interface-style declarations (requires/provides) are ports too.
            for iface in &comp.interfaces_in {
                let pname = c_ident(&iface.name);
                out.push_str(&format!(
                    "/* requires {} — implement this handler */\nvoid {prefix}_on_{pname}({});\n",
                    iface.name,
                    arg_for(&iface.name)
                ));
            }
            for iface in &comp.interfaces_out {
                let pname = c_ident(&iface.name);
                out.push_str(&format!(
                    "/* provides {} — provided by the integration layer */\nvoid {prefix}_send_{pname}({});\n",
                    iface.name,
                    arg_for(&iface.name)
                ));
            }
            out.push('\n');
        }
    }

    // ---- State machines ----
    if !ast.state_machines.is_empty() {
        out.push_str("/* ==== State machines ==== */\n\n");
    }
    for machine in &ast.state_machines {
        let mname = c_ident(&machine.name);
        out.push_str("typedef enum {\n");
        for state in &machine.states {
            out.push_str(&format!(
                "    {}_{},\n",
                mname.to_uppercase(),
                c_ident(&state.name).to_uppercase()
            ));
        }
        out.push_str(&format!("}} {mname}_state_t;\n"));
        out.push_str(&format!(
            "/* initial: {} ; returns the next state for a trigger */\n\
             {mname}_state_t {mname}_step({mname}_state_t current, const char *trigger);\n\n",
            machine.initial_state
        ));
    }

    out.push_str(&format!("#endif /* {guard} */\n"));
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::compiler::{Compiler, CompilerConfig};

    #[test]
    fn header_covers_types_ports_and_state_machines() {
        let flagship = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("examples/complete_emergency_braking_simple.arc");
        let result = Compiler::new(CompilerConfig::default())
            .compile_file(&flagship)
            .expect("compiles");
        let header = generate_c_headers(&result.semantic_model, &result.ast);

        assert!(header.contains("#ifndef ARCLANG_"));
        assert!(header.contains("#include <stdint.h>"));
        // enum from the data model
        assert!(header.contains("typedef enum"));
        // class struct
        assert!(header.contains("typedef struct"));
        // port handler and sender prototypes
        assert!(header.contains("_on_"));
        assert!(header.contains("_send_"));
        // state machine
        assert!(header.contains("_state_t"));
        assert!(header.contains("_step("));
        // deterministic
        assert_eq!(header, generate_c_headers(&result.semantic_model, &result.ast));
    }

    #[test]
    fn c_identifiers_are_sanitized() {
        assert_eq!(c_ident("Sensor Fusion"), "sensor_fusion");
        assert_eq!(c_ident("LC-001"), "lc_001");
        assert_eq!(c_ident("RadarFrame"), "radar_frame");
        assert_eq!(c_ident("42abc"), "_42abc");
    }
}
