//! Simulink / System Composer export.
//!
//! Emits a MATLAB script (.m) that rebuilds the architecture inside
//! MathWorks System Composer: components, oriented ports, typed connections,
//! and Stateflow skeletons for the model's state machines. The script is
//! plain text — its GENERATION is proven in CI; its execution belongs to a
//! licensed MATLAB environment.
//!
//! Scope (honest): architecture skeleton + interface contracts. Physical /
//! control behaviour stays in Simulink, as in the standard industrial split.

use super::ast::{Model, StateKind};
use super::semantic::SemanticModel;

/// A valid MATLAB identifier: letters/digits/underscore, starts with a
/// letter, at most 63 characters.
fn matlab_ident(raw: &str) -> String {
    let mut out = String::new();
    for c in raw.chars() {
        if c.is_ascii_alphanumeric() {
            out.push(c);
        } else if !out.is_empty() && !out.ends_with('_') {
            out.push('_');
        }
    }
    let trimmed = out.trim_matches('_');
    let mut ident = if trimmed.is_empty() { "X".to_string() } else { trimmed.to_string() };
    if !ident.chars().next().unwrap().is_ascii_alphabetic() {
        ident.insert(0, 'C');
    }
    ident.truncate(63);
    ident
}

fn m_string(text: &str) -> String {
    format!("'{}'", text.replace('\'', "''"))
}

pub fn generate_simulink_script(model: &SemanticModel, ast: &Model) -> String {
    let mut out = String::new();
    let model_name = matlab_ident(model.name.as_deref().unwrap_or("ArcLangModel"));

    out.push_str("%% Generated by ArcLang — System Composer architecture skeleton\n");
    out.push_str("% Run inside MATLAB (System Composer required).\n");
    out.push_str("% Mapping: component -> systemcomposer component, port in/out ->\n");
    out.push_str("% in/out port, exchange -> connection, state_machine -> Stateflow chart.\n\n");
    out.push_str(&format!("archModel = systemcomposer.createModel({}, true);\n", m_string(&model_name)));
    out.push_str("arch = archModel.Architecture;\n\n");

    // ---- Components with ports -------------------------------------------
    out.push_str("%% Components\n");
    let mut emitted_ports: std::collections::HashSet<(String, String)> =
        std::collections::HashSet::new();
    for component in &model.components {
        let ident = matlab_ident(&component.id);
        out.push_str(&format!(
            "comp_{ident} = addComponent(arch, {});\n",
            m_string(&component.name)
        ));
        if let Some(level) = &component.safety_level {
            out.push_str(&format!(
                "% {}: safety level {} (ArcLang uuid {})\n",
                component.name, level, component.uuid()
            ));
        }
        for port in &component.interfaces_in {
            out.push_str(&format!(
                "addPort(comp_{ident}.Architecture, {}, 'in');\n",
                m_string(&port.name)
            ));
            emitted_ports.insert((ident.clone(), port.name.clone()));
        }
        for port in &component.interfaces_out {
            out.push_str(&format!(
                "addPort(comp_{ident}.Architecture, {}, 'out');\n",
                m_string(&port.name)
            ));
            emitted_ports.insert((ident.clone(), port.name.clone()));
        }
    }
    // Explicit `port in|out` declarations from the logical architecture
    for la in &ast.logical_architecture {
        for component in &la.components {
            let key = if component.id.is_empty() { &component.name } else { &component.id };
            let ident = matlab_ident(key);
            for port in &component.ports {
                if !emitted_ports.insert((ident.clone(), port.name.clone())) {
                    continue;
                }
                let direction = match port.direction {
                    super::ast::PortDirection::In => "in",
                    super::ast::PortDirection::Out => "out",
                    super::ast::PortDirection::InOut => "physical",
                };
                out.push_str(&format!(
                    "addPort(comp_{ident}.Architecture, {}, {});\n",
                    m_string(&port.name),
                    m_string(direction)
                ));
            }
        }
    }
    out.push('\n');

    // ---- Connections from resolved exchanges ------------------------------
    out.push_str("%% Connections (exchanges)\n");
    let known: std::collections::HashSet<&str> =
        model.components.iter().map(|c| c.id.as_str()).collect();
    let resolve = |endpoint: &str| -> Option<String> {
        let root = endpoint.split('.').next().unwrap_or(endpoint);
        if known.contains(endpoint) {
            return Some(matlab_ident(endpoint));
        }
        if known.contains(root) {
            return Some(matlab_ident(root));
        }
        model
            .components
            .iter()
            .find(|c| c.name == endpoint || c.name == root)
            .map(|c| matlab_ident(&c.id))
    };
    for interface in &model.interfaces {
        if let (Some(source), Some(target)) = (resolve(&interface.from), resolve(&interface.to)) {
            if source != target {
                out.push_str(&format!(
                    "connect(arch, comp_{source}, comp_{target}); % {}\n",
                    interface.name
                ));
            }
        }
    }
    out.push('\n');

    // ---- Stateflow skeletons ----------------------------------------------
    if !ast.state_machines.is_empty() {
        out.push_str("%% Stateflow charts (behaviour skeletons)\n");
        out.push_str(&format!("sfModelName = {};\n", m_string(&format!("{model_name}_behaviour"))));
        out.push_str("sfnew(sfModelName);\nrt = sfroot;\nsfMachine = rt.find('-isa','Stateflow.Machine','Name',sfModelName);\n\n");
        for (machine_index, machine) in ast.state_machines.iter().enumerate() {
            let chart_var = format!("chart{machine_index}");
            out.push_str(&format!(
                "{chart_var} = Stateflow.Chart(sfMachine); {chart_var}.Name = {};\n",
                m_string(&machine.name)
            ));
            for (state_index, state) in machine.states.iter().enumerate() {
                let kind = if state.kind == StateKind::Mode { "mode" } else { "state" };
                out.push_str(&format!(
                    "s{machine_index}_{state_index} = Stateflow.State({chart_var}); s{machine_index}_{state_index}.Name = {}; s{machine_index}_{state_index}.Position = [{}, {}, 120, 60]; % {kind}\n",
                    m_string(&matlab_ident(&state.name)),
                    40 + (state_index % 4) * 180,
                    40 + (state_index / 4) * 120,
                ));
            }
            for transition in &machine.transitions {
                let find_index = |name: &str| machine.states.iter().position(|s| s.name == name);
                if let (Some(from), Some(to)) = (find_index(&transition.from), find_index(&transition.to)) {
                    let mut label = transition.trigger.clone();
                    if let Some(guard) = &transition.guard {
                        label.push_str(&format!("[{guard}]"));
                    }
                    out.push_str(&format!(
                        "t = Stateflow.Transition({chart_var}); t.Source = s{machine_index}_{from}; t.Destination = s{machine_index}_{to}; t.LabelString = {};\n",
                        m_string(&label)
                    ));
                }
            }
            out.push('\n');
        }
    }

    out.push_str("save_system(archModel.SimulinkHandle);\n");
    out.push_str(&format!("disp('ArcLang architecture {} generated.');\n", model_name));
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn matlab_identifiers_are_sanitized() {
        assert_eq!(matlab_ident("Brake Controller"), "Brake_Controller");
        assert_eq!(matlab_ident("REQ-AEB-001"), "REQ_AEB_001");
        assert_eq!(matlab_ident("42x"), "C42x");
    }

    #[test]
    fn script_contains_core_api_calls() {
        use crate::compiler::{Compiler, CompilerConfig};
        let source = r#"
model Demo {
}

architecture logical {
    component "Brake Controller" {
        id: "LC-001"
        port in Threat { }
        port out Command { }
        function "compute"
    }
    component "Actuator" { id: "LC-002" function "act" }
    component_exchange "cmd" { from_port: "LC-001" to_port: "LC-002" }
}

state_machine Modes {
    initial: "Off"
    mode Off { }
    mode Active { }
    transition Off -> Active { trigger: "engage" }
}
"#;
        let result = Compiler::new(CompilerConfig::default())
            .compile_string(source)
            .expect("compiles");
        let script = generate_simulink_script(&result.semantic_model, &result.ast);

        assert!(script.contains("systemcomposer.createModel('Demo'"));
        assert!(script.contains("addComponent(arch, 'Brake Controller')"));
        assert!(script.contains("addPort(comp_LC_001.Architecture, 'Threat', 'in')"));
        assert!(script.contains("connect(arch, comp_LC_001, comp_LC_002)"));
        assert!(script.contains("Stateflow.Chart"));
        assert!(script.contains("t.LabelString = 'engage'"));
    }
}
