//! SysML v2 textual notation export (interoperability subset).
//!
//! Emits an OMG SysML v2 textual model from the canonical semantic model:
//! `package`, `part def`/`part`, `action def`, `requirement def`,
//! `connect`, and `satisfy` statements. Element names that are not valid
//! SysML basic identifiers are emitted as unrestricted names ('...'), which
//! the SysML v2 grammar supports.
//!
//! Scope is documented and honest: attributes, ports, interfaces,
//! multiplicities, and behaviors beyond simple action defs are not emitted.

use super::semantic::SemanticModel;

/// A SysML v2 basic identifier: letter or underscore, then letters, digits,
/// underscores. Anything else must use the unrestricted-name form '...'.
fn sysml_name(raw: &str) -> String {
    let mut chars = raw.chars();
    let valid = match chars.next() {
        Some(first) if first.is_ascii_alphabetic() || first == '_' => {
            chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
        }
        _ => false,
    };
    if valid {
        raw.to_string()
    } else {
        format!("'{}'", raw.replace('\\', "\\\\").replace('\'', "\\'"))
    }
}

fn doc_comment(indent: &str, text: &str) -> String {
    format!("{indent}doc /* {} */\n", text.replace("*/", "* /"))
}

pub fn generate_sysmlv2(model: &SemanticModel) -> String {
    let mut out = String::new();
    let package_name = sysml_name(model.name.as_deref().unwrap_or("ArcLangModel"));

    out.push_str("// Generated by ArcLang — SysML v2 interoperability export\n");
    out.push_str("// Mapping: component -> part def/part, function -> action def,\n");
    out.push_str("//          requirement -> requirement def, exchange -> connect,\n");
    out.push_str("//          trace satisfies -> satisfy.\n");
    out.push_str(&format!("package {} {{\n\n", package_name));

    // Requirements
    if !model.requirements.is_empty() {
        out.push_str("    // ---- Requirements ----\n");
        for req in &model.requirements {
            out.push_str(&format!("    requirement def {} {{\n", sysml_name(&req.id)));
            if !req.description.is_empty() {
                out.push_str(&doc_comment("        ", &req.description));
            }
            out.push_str("    }\n");
        }
        out.push('\n');
    }

    // Functions as action definitions
    if !model.functions.is_empty() {
        out.push_str("    // ---- Functions ----\n");
        for function in &model.functions {
            out.push_str(&format!("    action def {};\n", sysml_name(&function.name)));
        }
        out.push('\n');
    }

    // Components as part definitions + usages
    if !model.components.is_empty() {
        out.push_str("    // ---- Components ----\n");
        for comp in &model.components {
            out.push_str(&format!("    part def {} {{\n", sysml_name(&comp.name)));
            out.push_str(&doc_comment(
                "        ",
                &format!("ArcLang id: {} | layer: {} | uuid: {}", comp.id, comp.level, comp.uuid()),
            ));
            for function_ref in &comp.functions {
                // Component function lists may hold ids or names; the action
                // def is declared by name, so resolve ids to names.
                let action = model
                    .functions
                    .iter()
                    .find(|f| &f.id == function_ref)
                    .map(|f| f.name.as_str())
                    .unwrap_or(function_ref);
                out.push_str(&format!("        perform action {};\n", sysml_name(action)));
            }
            out.push_str("    }\n");
            out.push_str(&format!(
                "    part {} : {};\n",
                sysml_name(&usage_name(&comp.id)),
                sysml_name(&comp.name)
            ));
        }
        out.push('\n');
    }

    // Exchanges as connections
    if !model.interfaces.is_empty() {
        out.push_str("    // ---- Exchanges ----\n");
        for interface in &model.interfaces {
            let from = resolve_usage(model, &interface.from);
            let to = resolve_usage(model, &interface.to);
            if let (Some(from), Some(to)) = (from, to) {
                out.push_str(&format!(
                    "    connect {} to {};  // {}\n",
                    sysml_name(&from),
                    sysml_name(&to),
                    interface.name
                ));
            }
        }
        out.push('\n');
    }

    // Traces as satisfy statements
    let satisfies: Vec<_> = model
        .traces
        .iter()
        .filter(|t| t.trace_type == "satisfies")
        .collect();
    if !satisfies.is_empty() {
        out.push_str("    // ---- Traceability ----\n");
        for trace in satisfies {
            out.push_str(&format!(
                "    satisfy {} by {};\n",
                sysml_name(&trace.to),
                sysml_name(&usage_name(&trace.from))
            ));
        }
        out.push('\n');
    }

    out.push_str("}\n");
    out
}

/// Part-usage name derived from the ArcLang element id.
fn usage_name(id: &str) -> String {
    let mut name = String::from("p_");
    for c in id.chars() {
        name.push(if c.is_ascii_alphanumeric() { c } else { '_' });
    }
    name
}

/// Resolve an exchange endpoint (id, name, or dotted path) to a part usage name.
fn resolve_usage(model: &SemanticModel, endpoint: &str) -> Option<String> {
    let root = endpoint.split('.').next().unwrap_or(endpoint);
    for candidate in [endpoint, root] {
        if model.all_elements.contains_key(candidate) {
            return Some(usage_name(candidate));
        }
        if let Some(comp) = model.components.iter().find(|c| c.name == candidate) {
            return Some(usage_name(&comp.id));
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn plain_names_stay_basic_identifiers() {
        assert_eq!(sysml_name("BrakeController"), "BrakeController");
        assert_eq!(sysml_name("_x1"), "_x1");
    }

    #[test]
    fn names_with_spaces_or_symbols_become_unrestricted() {
        assert_eq!(sysml_name("Brake Controller"), "'Brake Controller'");
        assert_eq!(sysml_name("REQ-001"), "'REQ-001'");
        assert_eq!(sysml_name("O'Brien"), "'O\\'Brien'");
    }

    #[test]
    fn export_contains_core_constructs() {
        use crate::compiler::{Compiler, CompilerConfig};
        let source = r#"
model Demo {
}

requirements safety {
    req "REQ-001" "Braking" { description: "Brake on demand" }
}

architecture logical {
    component "BrakeController" {
        id: "LC-001"
        function "Compute force"
    }
}

trace "LC-001" satisfies "REQ-001" { rationale: "direct" }
"#;
        let result = Compiler::new(CompilerConfig::default())
            .compile_string(source)
            .expect("compiles");
        let sysml = generate_sysmlv2(&result.semantic_model);

        assert!(sysml.contains("package Demo {"));
        assert!(sysml.contains("requirement def 'REQ-001'"));
        assert!(sysml.contains("part def BrakeController {"));
        assert!(sysml.contains("part p_LC_001 : BrakeController;"));
        assert!(sysml.contains("satisfy 'REQ-001' by p_LC_001;"));
    }
}
